---
title: "Implementing New Methods in `impart`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Implementing New Methods in `impart`}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{pwr}
  %\VignetteDepends{ggplot2}
---

```{r RMD-Setup, include = FALSE}
fig_w <- 8
fig_h <- 8

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE,
  message = TRUE,
  error = TRUE,
  purl = FALSE,
  results = "markup",
  fig.path = "../man/figures/",
  fig.width = fig_w,
  fig.height = fig_h,
  fig.align = "center",
  out.width = "80%",
  dpi = 600
)

options(
  rmarkdown.html_vignette.check_title = FALSE
)

set.seed(9876)
```

`impart` has built-in methods for covariate adjustment that allow for continuous and binary outcomes, but is designed to be able to use methods from other R packages. This vignette demonstrates how to use new methods with `impart`, allowing new software to be used in information monitoring and group sequential designs.




```{r}
library(speff2trial)
# Extract two treatment arms: Lev+5FU (Chemotherapy) and Obs (Observation)
colon_cancer_5fu_vs_obs <-
  subset(
    x = colon_cancer,
    arm %in% c("Lev+5FU", "Obs")
  ) |>
  droplevels()
  

sp_unadjusted <-
  survival::coxph(
    formula =
      survival::Surv(time = years_to_death, event = event_death) ~ arm,
    data = colon_cancer_5fu_vs_obs
  )

sp_full <-
  speff2trial::speffSurv(
    formula =
      survival::Surv(time = years_to_death, event = event_death) ~
      age + sex + obstruction + perforation + organ_adherence + positive_nodes +
      differentiation +local_spread,
    data = colon_cancer_5fu_vs_obs,
    trt.id = "arm",
    fixed = TRUE
  )
```
